name: rtd
channels:
- dean0x7d
dependencies:
- cmake=3.3.1=0
- cycler=0.9.0=py34_0
- eigen3=3.2.7=0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libxml2=2.9.2=0
- matplotlib=1.5.1=np110py34_0
- numpy=1.10.4=py34_nomkl_0
- openblas=0.2.14=3
- openssl=1.0.2d=0
- pip=8.0.2=py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.11.4=py34_1
- python=3.4.4=0
- python-dateutil=2.4.2=py34_0
- pytz=2015.7=py34_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.17.0=np110py34_nomkl_1
- setuptools=19.6.2=py34_0
- sip=4.16.9=py34_0
- six=1.10.0=py34_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.26.0=py34_1
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - numpydoc==0.5
