name: rtd
dependencies:
- cmake=3.3.1=0
- cycler=0.10.0=py34_0
- decorator=4.0.9=py34_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- ipython_genutils=0.1.0=py34_0
- jinja2=2.8=py34_0
- jsonschema=2.4.0=py34_0
- jupyter_core=4.0.6=py34_0
- libgfortran=3.0=0
- libpng=1.6.17=0
- libxml2=2.9.2=0
- markupsafe=0.23=py34_0
- matplotlib=1.5.1=np110py34_0
- mistune=0.7.1=py34_0
- nbconvert=4.1.0=py34_0
- nbformat=4.0.1=py34_0
- nomkl=1.0=0
- numpy=1.10.4=py34_nomkl_1
- openblas=0.2.14=4
- openssl=1.0.2g=0
- pip=8.1.0=py34_0
- pygments=2.1.1=py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.11.4=py34_1
- python=3.4.4=0
- python-dateutil=2.4.2=py34_0
- pytz=2015.7=py34_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.17.0=np110py34_nomkl_2
- setuptools=20.2.2=py34_0
- sip=4.16.9=py34_0
- six=1.10.0=py34_0
- sphinx_rtd_theme=0.1.9=py34_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- traitlets=4.1.0=py34_0
- wheel=0.29.0=py34_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - numpydoc==0.6.0
