language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  - PYTHON=3.4

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - source ./support/travis_general.sh
  - source ./support/travis_cmake.sh
  - source ./support/travis_miniconda.sh
install:
  - python setup.py build_ext
  - python setup.py install
script:
  - py.test
