name: build-wheel

permissions:
  contents: write
on:
  workflow_run:
    workflows: ["cmake-compile-tests"]
    types:
      - completed
    branches:
      - master

jobs:
  build-all-all:
    name: Build on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    env:
      PB_BUILD_TYPE: Release
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies Pybinding
        run: python -m pip install wheel scipy matplotlib pytest cmake ninja build
      - name: Set up MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
      - name: Build wheel
        run: python -m pip --sdist --wheel --outdir dist/
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python-version }}-${{ matrix.os }}-artefacts
          path: dist