name: release

on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed
    branches:
      - master

permissions:
  contents: write

jobs:
  documentation:
    name: Make and upload the documentation
    runs-on: ubuntu-latest
    env:
      PB_BUILD_TYPE: Release
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies Pybinding
        run: python -m pip install wheel scipy matplotlib pytest cmake ninja sphinx-rtd-theme recommonmark numpydoc nbconvert
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
      - name: Test Documentation
        run: mkdir build_tests && cd build_tests && cmake .. && cmake --build . --target docs && ls && pwd && touch docs/html/.nojekyll
      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build_tests/docs/html

#  publish:
#    name: Compile and publish the package to PyPI
#    runs-on: ${{ matrix.os }}
#    env:
#      PB_BUILD_TYPE: Release
#    strategy:
#      matrix:
#        os: [ windows-latest, macos-latest, ubuntu-latest ]
#        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          submodules: true
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v4
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Install dependencies Pybinding
#        run: python -m pip install wheel scipy matplotlib pytest cmake ninja
#      - name: Set up MSVC
#        if: runner.os == 'Windows'
#        uses: ilammy/msvc-dev-cmd@v1
#      - name: ccache
#        uses: hendrikmuhs/ccache-action@v1
#      - name: Build with pip
#        run: python -m pip install .
#      - name: Test Python
#        run: python -c "import pybinding as pb; exit(pb.tests())"
