name: test-wheel

on:
  workflow_run:
    workflows: ["build-wheel"]
    types:
      - completed
    branches:
      - master

jobs:
  build-all-all:
    name: Test wheel on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download wheel for ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.python-version }}-${{ matrix.os }}-artefacts
          path: dist
      - name: Install Pybinding
        run: python -m pip install dist/*.whl
      - name: Test Python
        run: python -c "import pybinding as pb; exit(pb.tests())"
