name: tests and publish

on: [push]
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies Pybinding
      run: python -m pip install wheel scipy matplotlib pytest cmake ninja
    - name: Set up MSVC
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build with CMake and test Python / C++
      run: mkdir build_tests && cd build_tests && cmake .. && make tests && cd ..
    - name: Build with pip
      run: python -m pip install .
    - name: Test Python
      run: python -c "import pybinding as pb; exit(pb.tests())"
    - name: Install dependencies Docs
      run: python -m pip install sphinx-rtd-theme recommonmark numpydoc nbconvert
    - name: Test Documentation
      run: cd build_tests && make docs
    - name: Publish docs
      if: runner.os == 'Ubuntu'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/html



